import Head from "next/head";
import { useRouter } from "next/router";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import { HomeNav } from "./components/Home/HomeNav";
import { HomeFooter } from "./components/Home/HomeFooter";

export default function HomePage() {
  const router = useRouter();
  const { data: sessionData } = useSession();
  const { data: boards } = trpc.boards.getAllBoards.useQuery();
  if (sessionData) {
    if (boards) {
      router.push(`/boards/${boards?.[0]?.id}`);
    }
  }

  return (
    <>
      <Head>
        <title>Kanban</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <HomeNav />
        {/* <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          <button onClick={() => signIn()}>Sign in</button>
        </div> */}
        {/* <AuthShowcase /> */}
        <Hero />
        {/* <HomeFooter /> */}
      </main>
    </>
  );
}

const Hero = () => {
  return (
    <div className="mx-auto w-11/12">
      <div className="mb-2">
        <h2 className="heading-l">One place with everything you need.</h2>
        <span className="body-m font-medium">
          Plan better. Get work done faster.
        </span>
      </div>
      <div className="mx-auto mb-2 w-10/12 max-w-[650px] ">
        <img
          src="img/landingPage1.svg"
          alt="Product Example"
          className="rounded-lg shadow-lg"
        />
      </div>
      <div className="mx-auto w-10/12 max-w-[650px] ">
        <img
          src="img/landingPage2.svg"
          alt="Product Example"
          className="rounded-lg shadow-lg "
        />
      </div>
    </div>
  );
};

// const AuthShowcase: React.FC = () => {
//   const router = useRouter();
//   const { data: sessionData } = useSession();

//   return (
//     <div className="flex flex-col items-center justify-center gap-2">
//       {sessionData && (
//         <>
//           <p className="text-2xl text-blue-500">
//             Logged in as {sessionData?.user?.name}
//           </p>
//           <img
//             src={sessionData?.user?.image}
//             alt="avatar"
//             className="rounded-full"
//           />
//         </>
//       )}
//     </div>
//   );
// };
